# navigation
[nav]
home = "首页"
guide = "快速入门"
community = "开发社区"
docs = "开发文档"
video = "开发视频"
products = "产品案例"
blog = "博客"

# about post
[post]
list = "所有文章"
archive = "归档"
tag = "标签"
readmore = "继续阅读"

# about pagination
[pager]
prev = "更新的"
next = "以前的"